export function translateErrorCodeAPI(code: any) {
    const objCodes = {
        0: 'Captura Efetuada com Sucesso',
        101: 'Captura n�o Autorizada. Problemas no cart�o, entre em contate com o emissor',
        102: 'Captura n�o Autorizada. Verifique a situa��o da loja com o emissor',
        103: 'Captura n�o Autorizada. Por favor tente novamente',
        104: 'Captura n�o Autorizada. Por favor tente novamente',
        105: 'Captura n�o Autorizada. Cart�o com restri��o',
        106: 'Erro no processamento do emissor. Por favor tente novamente',
        107: 'Captura n�o Autorizada. Por favor tente novamente',
        108: 'Captura n�o Autorizada. Valor n�o permitido para este tipo de cart�o',
        109: 'Captura n�o Autorizada. Cart�o n�o existe',
        110: 'Captura n�o Autorizada. Tipo de transa��o n�o permitida para este cart�o',
        111: 'Captura n�o Autorizada. Sem limite no cart�o',
        112: 'Captura n�o Autorizada. Data de validade expirada',
        113: 'Captura n�o Autorizada. Identificado risco moderado pelo emissor',
        114: 'Captura n�o Autorizada. O cart�o n�o pertence a rede de pagamento',
        115: 'Captura n�o Autorizada. Excedeu o limite de transa��es permitidas no per�odo',
        116: 'Captura n�o Autorizada. Entre em contato com o emissor do cart�o',
        117: 'Transa��o n�o encontrada',
        118: 'Captura n�o Autorizada. Cart�o bloqueado',
        119: 'Captura n�o Autorizada. C�digo de seguran�a inv�lido',
        121: 'Erro ao processar. Por favor tente novamente',
        122: 'Transa��o enviada anteriormente',
        123: 'Captura n�o Autorizada. O portador solicitou o fim das recorr�ncias no emissor',
        124: 'Captura n�o Autorizada. Entre em contato com a Rede',
        170: 'Transa��o com valor zerado n�o permitida para este cart�o',
        174: 'Transa��o com valor zerado efetuada com sucesso',
        175: 'Transa��o com valor zerado negada',
        1: 'expirationYear: Tamanho do par�metro inv�lido',
        2: 'expirationYear: Formato do par�metro inv�lido',
        3: 'expirationYear: Par�metro obrigat�rio ausente',
        4: 'cavv: Tamanho do par�metro inv�lido',
        5: 'cavv: Formato do par�metro inv�lido',
        6: 'postalCode: Tamanho do par�metro inv�lido',
        7: 'postalCode: Formato do par�metro inv�lido',
        8: 'postalCode: Par�metro obrigat�rio ausente',
        9: 'complement: Tamanho do par�metro inv�lido',
        10: 'complement: Formato do par�metro inv�lido',
        11: 'departureTax: Formato do par�metro inv�lido',
        12: 'documentNumber: Tamanho do par�metro inv�lido',
        13: 'documentNumber: Formato do par�metro inv�lido',
        14: 'documentNumber: Par�metro obrigat�rio ausente',
        15: 'securityCode: Tamanho do par�metro inv�lido',
        16: 'securityCode: Formato do par�metro inv�lido',
        17: 'distributorAffiliation: Tamanho do par�metro inv�lido',
        18: 'distributorAffiliation: Formato do par�metro inv�lido',
        19: 'xid: Tamanho do par�metro inv�lido',
        20: 'eci: Formato do par�metro inv�lido',
        21: 'xid: Par�metro obrigat�rio ausente para o cart�o Visa',
        22: 'street: Par�metro obrigat�rio ausente',
        23: 'street: Formato do par�metro inv�lido',
        24: 'affiliation: Tamanho do par�metro inv�lido',
        25: 'affiliation: Formato do par�metro inv�lido',
        26: 'affiliation: Par�metro obrigat�rio ausente',
        27: 'Par�metro cavv ou eci ausente',
        28: 'code: Tamanho do par�metro inv�lido',
        29: 'code: Formato do par�metro inv�lido',
        30: 'code: Par�metro obrigat�rio ausente',
        31: 'softdescriptor: Tamanho do par�metro inv�lido',
        32: 'softdescriptor: Formato do par�metro inv�lido',
        33: 'expirationMonth: Formato do par�metro inv�lido',
        34: 'code: Formato do par�metro inv�lido',
        35: 'expirationMonth: Par�metro obrigat�rio ausente',
        36: 'cardNumber: Tamanho do par�metro inv�lido',
        37: 'cardNumber: Formato do par�metro inv�lido',
        38: 'cardNumber: Par�metro obrigat�rio ausente',
        39: 'reference: Tamanho do par�metro inv�lido',
        40: 'reference: Formato do par�metro inv�lido',
        41: 'reference: Par�metro obrigat�rio ausente',
        42: 'reference: N�mero do pedido j� existe',
        43: 'number: Tamanho do par�metro inv�lido',
        44: 'number: Formato do par�metro inv�lido',
        45: 'number: Par�metro obrigat�rio ausente',
        46: 'installments: N�o correspondem � transa��o de autoriza��o',
        47: 'origin: Formato do par�metro inv�lido',
        49: 'O valor da transa��o excede o autorizado',
        50: 'installments: Formato do par�metro inv�lido',
        51: 'Produto ou servi�o desabilitado para este comerciante. Entre em contato com a Rede',
        53: 'Transa��o n�o autorizada pelo emissor. Entre em contato com a Rede',
        54: 'installments: Par�metro n�o permitido para este transa��o',
        55: 'cardHolderName: Tamanho do par�metro inv�lido',
        56: 'Erro nos dados enviados. Tente novamente',
        57: 'affiliation: Comerciante inv�lido',
        58: 'N�o autorizado. Entre em conato com o emissor',
        59: 'cardHolderName: Formato do par�metro inv�lido',
        60: 'street: Tamanho do par�metro inv�lido',
        61: 'subscription: Formato do par�metro inv�lido',
        63: 'softdescriptor: N�o habilitado para este comerciante',
        64: 'Transa��o n�o processada. Tente Novamente',
        65: 'token: Token inv�lido',
        66: 'departureTax: Tamanho do par�metro inv�lido',
        67: 'departureTax: Formato do par�metro inv�lido',
        68: 'departureTax: Par�metro obrigat�rio ausente',
        69: 'Transa��o n�o permitida para este produto ou servi�o',
        70: 'amount: Tamanho do par�metro inv�lido',
        71: 'amount: Formato do par�metro inv�lido',
        72: 'Entre em contato com o emissor',
        73: 'amount: Par�metro obrigat�rio ausente',
        74: 'Falha na comunica��o. Tente novamente',
        75: 'departureTax: Este par�metro n�o deve ser enviado para este tipo de transa��o',
        76: 'kind: Formato do par�metro inv�lido',
        78: 'Transa��o n�o existe',
        79: 'Cart�o vencido. A transa��o n�o pode ser reenviada. Entre em contato com o emissor',
        80: 'N�o autorizada. Entre em contato com o emissor (Sem limite de cr�dito',
        82: 'Transa��o n�o autorizada para cart�o de d�bito',
        83: 'N�o autorizada. Entre em contato com o emissor',
        84: 'N�o autorizada. A transa��o n�o pode ser reenviada. Entre em contato com o emissor',
        85: 'complement: Tamanho do par�metro inv�lido',
        86: 'Cart�o vencido',
        87: 'Ao menos um dos campos a seguir precisam ser preenchidos: tid ou reference',
        88: 'Comerciante n�o aprovado. Regularize seu site e entre em contato com a Rede para retornar � transa��o.',
        89: 'token: Token inv�lido',
        97: 'tid: Tamanho do par�metro inv�lido',
        98: 'tid: Formato do par�metro inv�lido',
        132: 'DirectoryServerTransactionId: Tamanho do par�metro inv�lido',
        133: 'ThreedIndicator: Valor do par�metro inv�lido',
        150: 'Tempo esgotado. Tente novamente',
        151: 'installments: Maior que o permitido',
        153: 'documentNumber: N�mero inv�lido',
        154: 'embedded: Formato do par�metro inv�lido',
        155: 'eci: Par�metro obrigat�rio ausente',
        156: 'eci: Tamanho do par�metro inv�lido',
        157: 'cavv: Par�metro obrigat�rio ausente',
        158: 'capture: Tipo n�o permitido para esta transa��o',
        159: 'userAgent: Tamanho do par�metro inv�lido',
        160: 'urls: Par�metro obrigat�rio ausente (tipo',
        161: 'urls: Formato do par�metro inv�lido',
        167: 'Requisi��o JSON inv�lida',
        169: 'Content-Type inv�lido',
        171: 'Opera��o n�o permitida para esta transa��o',
        173: 'Autoriza��o expirou',
        176: 'urls: Par�metro obrigat�rio ausente (url',
        899: 'Sem sucesso. Por favor entre em contato com a Rede',
        370: 'Requisi��o falhou. Entre em contato com a Rede',
        1018: 'Tamanho do MCC inv�lido',
        1019: 'Par�metro MCC obrigat�rio',
        1020: 'Formato do MCC inv�lido',
        1021: 'PaymentFacilitatorID Tamanho inv�lido',
        1023: 'PaymentFacilitatorID Formato inv�lido',
        1030: 'CitySubMerchant Tamanho inv�lido',
        1034: 'CountrySubMerchant Tamanho inv�lido',
    };

    const exception = objCodes[code] || objCodes[500];
    return exception;
}
